ALTER TABLE IF EXISTS ft_user
  ADD COLUMN IF NOT EXISTS "isAppUser" BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "hasAcceptedTerms" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "termsVersion" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMPTZ;
