INSERT INTO ft_relationship_translations ("languageCode", "fromLevel", "toLevel", "fromGender", "toGender", "relationKey", "relationName", "notes", "createdAt", "updatedAt"
) VALUES('ta', 3, 5, 'male', 'male', 'great_great_great_grandfather', 'பூட்டன்', '5 generations back', NOW(), NOW()),
('ta', 3, 5, 'male', 'female', 'great_great_great_grandmother', 'பூட்டி', '5 generations back', NOW(), NOW()),
('ta', 3, 5, 'female', 'male', 'great_great_great_grandfather', 'பூட்டன்', '5 generations back', NOW(), NOW()),
('ta', 3, 5, 'female', 'female', 'great_great_great_grandmother', 'பூட்டி', '5 generations back', NOW(), NOW()),
('ta', 3, 4, 'male', 'male', 'great_great_grandfather', 'ஓட்டன்', '4 generations back', NOW(), NOW()),
('ta', 3, 4, 'male', 'female', 'great_great_grandmother', 'ஓட்டி', '4 generations back', NOW(), NOW()),
('ta', 3, 4, 'female', 'male', 'great_great_grandfather', 'ஓட்டன்', '4 generations back', NOW(), NOW()),
('ta', 3, 4, 'female', 'female', 'great_great_grandmother', 'ஓட்டி', '4 generations back', NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'great_grandfather', 'கொள்ளுத்தாத்தா', '3 generations back', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'great_grandmother', 'கொள்ளுப்பாட்டி', '3 generations back', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'great_grandfather', 'கொள்ளுத்தாத்தா', '3 generations back', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'great_grandmother', 'கொள்ளுப்பாட்டி', '3 generations back', NOW(), NOW()),
('ta', 3, 2, 'male', 'male', 'grandfather_paternal', 'தாத்தா', 'Fathers father', NOW(), NOW()),
('ta', 3, 2, 'male', 'female', 'grandmother_paternal', 'பாட்டி', 'Fathers mother', NOW(), NOW()),
('ta', 3, 2, 'female', 'male', 'grandfather_maternal', 'தாத்தா', 'Mothers father', NOW(), NOW()),
('ta', 3, 2, 'female', 'female', 'grandmother_maternal', 'பாட்டி', 'Mothers mother', NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'father', 'அப்பா', NULL, NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'mother', 'அம்மா', NULL, NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'father', 'அப்பா', NULL, NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'mother', 'அம்மா', NULL, NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'elder_brother', 'அண்ணன்', 'From male perspective', NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'younger_brother', 'தம்பி', 'From male perspective', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'elder_sister', 'அக்கா', 'From male perspective', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'younger_sister', 'தங்கை', 'From male perspective', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'elder_brother', 'அண்ணன்', 'From female perspective', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'younger_brother', 'தம்பி', 'From female perspective', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'elder_sister', 'அக்கா', 'From female perspective', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'younger_sister', 'தங்கை', 'From female perspective', NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'brother_general', 'சகோதரர்', 'General term for brother', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'sister_general', 'சகோதரி', 'General term for sister', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'brother_general', 'சகோதரர்', 'General term for brother', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'sister_general', 'சகோதரி', 'General term for sister', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'wife', 'மனைவி', NULL, NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'husband', 'கணவர்', NULL, NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'paternal_elder_uncle', 'பெரியப்பா', 'Father''s elder brother', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'paternal_elder_aunt', 'பெரியம்மா', 'Father''s elder brother''s wife', NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'paternal_younger_uncle', 'சித்தப்பா', 'Father''s younger brother', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'paternal_younger_aunt', 'சித்தி', 'Father''s younger brother''s wife (also சின்னம்மா)', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'paternal_aunt', 'அத்தை', 'Father''s sister', NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'paternal_elder_uncle', 'பெரியப்பா', 'Father''s elder brother', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'paternal_elder_aunt', 'பெரியம்மா', 'Father''s elder brother''s wife', NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'paternal_younger_uncle', 'சித்தப்பா', 'Father''s younger brother', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'paternal_younger_aunt', 'சித்தி', 'Father''s younger brother''s wife (also சின்னம்மா)', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'paternal_aunt', 'அத்தை', 'Father''s sister', NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'maternal_uncle', 'மாமா', 'Mother''s brother', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'maternal_aunt', 'மாமி', 'Mother''s brother''s wife', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'maternal_elder_aunt', 'பெரியம்மா', 'Mother''s elder sister', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'maternal_younger_aunt', 'சித்தி', 'Mother''s younger sister (also சின்னம்மா)', NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'maternal_uncle', 'மாமா', 'Mother''s brother', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'maternal_aunt', 'மாமி', 'Mother''s brother''s wife', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'maternal_elder_aunt', 'பெரியம்மா', 'Mother''s elder sister', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'maternal_younger_aunt', 'சித்தி', 'Mother''s younger sister (also சின்னம்மா)', NOW(), NOW()),
('ta', 3, 2, 'male', 'male', 'son', 'மகன்', NULL, NOW(), NOW()),
('ta', 3, 2, 'male', 'female', 'daughter', 'மகள்', NULL, NOW(), NOW()),
('ta', 3, 2, 'female', 'male', 'son', 'மகன்', NULL, NOW(), NOW()),
('ta', 3, 2, 'female', 'female', 'daughter', 'மகள்', NULL, NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'grandson', 'பேரன்', 'Son of one''s child', NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'granddaughter', 'பேர்த்தி', 'Daughter of one''s child', NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'grandson', 'பேரன்', 'Son of one''s child', NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'granddaughter', 'பேர்த்தி', 'Daughter of one''s child', NOW(), NOW()),
('ta', 3, 0, 'male', 'male', 'great_grandson', 'கொள்ளுப்பேரன்', 'Grandson of one''s child', NOW(), NOW()),
('ta', 3, 0, 'male', 'female', 'great_granddaughter', 'கொள்ளுப்பேர்த்தி', 'Granddaughter of one''s child', NOW(), NOW()),
('ta', 3, 0, 'female', 'male', 'great_grandson', 'கொள்ளுப்பேரன்', 'Grandson of one''s child', NOW(), NOW()),
('ta', 3, 0, 'female', 'female', 'great_granddaughter', 'கொள்ளுப்பேர்த்தி', 'Granddaughter of one''s child', NOW(), NOW()),
('ta', 3, -1, 'male', 'male', 'great_great_grandson', 'எள்ளுப்பேரன்', 'Great-grandson of one''s child', NOW(), NOW()),
('ta', 3, -1, 'male', 'female', 'great_great_granddaughter', 'எள்ளுப்பேர்த்தி', 'Great-granddaughter of one''s child', NOW(), NOW()),
('ta', 3, -1, 'female', 'male', 'great_great_grandson', 'எள்ளுப்பேரன்', 'Great-grandson of one''s child', NOW(), NOW()),
('ta', 3, -1, 'female', 'female', 'great_great_granddaughter', 'எள்ளுப்பேர்த்தி', 'Great-granddaughter of one''s child', NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'male_cross_cousin', 'மச்சான்', 'Son of aunt or uncle (from cross-sex sibling side). Can also mean brother-in-law.', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'female_cross_cousin', 'மச்சின்', 'Daughter of aunt or uncle (from cross-sex sibling side). Can also mean sister-in-law.', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'male_cross_cousin', 'மச்சான்', 'Son of aunt or uncle (from cross-sex sibling side). Can also mean brother-in-law.', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'female_cross_cousin', 'மச்சின்', 'Daughter of aunt or uncle (from cross-sex sibling side). Can also mean sister-in-law.', NOW(), NOW()),
('ta', 3, 1, 'male', 'male', 'father_in_law', 'மாமனார்', NULL, NOW(), NOW()),
('ta', 3, 1, 'male', 'female', 'mother_in_law', 'மாமியார்', NULL, NOW(), NOW()),
('ta', 3, 1, 'female', 'male', 'father_in_law', 'மாமனார்', NULL, NOW(), NOW()),
('ta', 3, 1, 'female', 'female', 'mother_in_law', 'மாமியார்', NULL, NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'brother_in_law_spouse_brother', 'மச்சான்', 'Wife''s brother / Husband''s younger brother. Also used for cross-cousin.', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'sister_in_law_spouse_sister', 'மச்சின்', 'Wife''s sister / Husband''s sister. Also used for cross-cousin.', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'brother_in_law_spouse_brother', 'மச்சான்', 'Husband''s younger brother / Wife''s brother. Also used for cross-cousin.', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'sister_in_law_spouse_sister', 'மச்சின்', 'Husband''s sister / Wife''s sister. Also used for cross-cousin.', NOW(), NOW()),
('ta', 3, 3, 'male', 'female', 'elder_brother_wife', 'அண்ணி', 'Elder brother''s wife', NOW(), NOW()),
('ta', 3, 3, 'male', 'male', 'elder_sister_husband', 'அத்தான்', 'Elder sister''s husband. Often also Machaan.', NOW(), NOW()),
('ta', 3, 3, 'female', 'female', 'younger_brother_wife', 'கொழுந்தியாள்', 'Younger brother''s wife', NOW(), NOW()),
('ta', 3, 3, 'female', 'male', 'younger_sister_husband', 'மாப்பிள்ளை', 'Younger sister''s husband. Often also Machaan.', NOW(), NOW()),
('ta', 3, 2, 'male', 'male', 'nephew_sibling_son', 'மருமகன்', 'General term for sibling''s son. Can also mean grandson/son-in-law.', NOW(), NOW()),
('ta', 3, 2, 'male', 'female', 'niece_sibling_daughter', 'மருமகள்', 'General term for sibling''s daughter. Can also mean granddaughter/daughter-in-law.', NOW(), NOW()),
('ta', 3, 2, 'female', 'male', 'nephew_sibling_son', 'மருமகன்', 'General term for sibling''s son. Can also mean grandson/son-in-law.', NOW(), NOW()),
('ta', 3, 2, 'female', 'female', 'niece_sibling_daughter', 'மருமகள்', 'General term for sibling''s daughter. Can also mean granddaughter/daughter-in-law.', NOW(), NOW()),
('ta', 3, 2, 'male', 'male', 'nephew_elder_brother_son', 'அண்ணன் மகன்', 'Son of elder brother', NOW(), NOW()),
('ta', 3, 2, 'male', 'female', 'niece_elder_brother_daughter', 'அண்ணன் மகள்', 'Daughter of elder brother', NOW(), NOW()),
('ta', 3, 2, 'male', 'male', 'nephew_younger_brother_son', 'தம்பி மகன்', 'Son of younger brother', NOW(), NOW()),
('ta', 3, 2, 'male', 'female', 'niece_younger_brother_daughter', 'தம்பி மகள்', 'Daughter of younger brother', NOW(), NOW()),
('ta', 3, 2, 'female', 'male', 'nephew_elder_sister_son', 'அக்கா மகன்', 'Son of elder sister', NOW(), NOW()),
('ta', 3, 2, 'female', 'female', 'niece_elder_sister_daughter', 'அக்கா மகள்', 'Daughter of elder sister', NOW(), NOW()),
('ta', 3, 2, 'female', 'male', 'nephew_younger_sister_son', 'தங்கை மகன்', 'Son of younger sister', NOW(), NOW()),
('ta', 3, 2, 'female', 'female', 'niece_younger_sister_daughter', 'தங்கை மகள்', 'Daughter of younger sister', NOW(), NOW()),
('ta', 0, 0, 'male', 'male', 'relative', 'உறவினர்', 'Generic relative', NOW(), NOW()),
('ta', 0, 0, 'male', 'female', 'relative', 'உறவினர்', 'Generic relative', NOW(), NOW()),
('ta', 0, 0, 'female', 'male', 'relative', 'உறவினர்', 'Generic relative', NOW(), NOW()),
('ta', 0, 0, 'female', 'female', 'relative', 'உறவினர்', 'Generic relative', NOW(), NOW());